kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
  name: sonar
  namespace: openshift-operators
  labels:
    app: sonar
spec:
  host: sonar-openshift-operators.crc-lgph7-master-0.crc.e8e64fephamw.instruqt.io
  to:
    kind: Service
    name: sonar
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
